--사원정보
--		사번, 이름, 직급명, 부서명, 급여, 입사일
CREATE TABLE EMPLOYEE(
	EMP_NO CHAR(8) PRIMARY KEY,
	EMP_NAME VARCHAR2(15) NOT NULL,
	EMP_POSITION VARCHAR2(30) DEFAULT '사원' NOT NULL,
	EMP_DEPARTMENT VARCHAR2(30),
	EMP_SALARY NUMBER(12) DEFAULT 0,
	EMP_COURSE_DATE DATE DEFAULT SYSDATE
);

SELECT SYSDATE FROM DUAL; --DUAL 임시 테이블, 값이나 연산결과 확인할때 주로 사용



