--그룹 함수
--	테이블에 있는 데이터를 특정 컬럼을 기준으로 통계 값을 구하는 함수
--	SUM, AVG, COUNT, MAX, MIN, STDDEV, VARIANCE
-- 	SELECT 학과, AVG(평점) FROM 학생 GROUP BY 학과;
--	그룹함수 사용한 컬럼과, 그룹으로 묶은 컬럼만 조회가 가능
--	학과별 평점 총합을 조회
SELECT STD_MAJOR, SUM(STD_SCORE) AS TOTAL_SCORE 
FROM NEW_STUDENT
GROUP BY STD_MAJOR;
-- 학과별 평점 평균 조회
SELECT STD_MAJOR, TRUNC(AVG(STD_SCORE),2) AS AVG_SCORE 
FROM NEW_STUDENT
GROUP BY STD_MAJOR;
-- 학과별 평점의 최대값, 최소값을 조회
SELECT STD_MAJOR, MAX(STD_SCORE), MIN(STD_SCORE), COUNT(*)  
FROM NEW_STUDENT
GROUP BY STD_MAJOR;
-- 학과별 인원수를 조회, 평점이 3.0 이상인 학생들만 조회
SELECT STD_MAJOR, COUNT(*) AS MAJOR_COUNT
FROM NEW_STUDENT
WHERE STD_SCORE >= 3
GROUP BY STD_MAJOR; 





