--사원정보
--		사번, 이름, 직급명, 부서명, 급여, 입사일
CREATE TABLE EMPLOYEE(
	EMP_NO CHAR(9) PRIMARY KEY,
	EMP_NAME VARCHAR2(15) NOT NULL,
	EMP_POSITION VARCHAR2(30) DEFAULT '사원' NOT NULL,
	EMP_DEPARTMENT VARCHAR2(30),
	EMP_SALARY NUMBER(12) DEFAULT 0,
	EMP_COURSE_DATE DATE DEFAULT SYSDATE
);

SELECT SYSDATE FROM DUAL; --DUAL 임시 테이블, 값이나 연산결과 확인할때 주로 사용

CREATE TABLE PERSON(
	PNAME VARCHAR2(30),
	AGE NUMBER(3)
);
--DML(데이터 조작어)
--	INSERT, DELETE, UPDATE, SELECT

--INSERT INTO 테이블명(컬럼명1, 컬럼명2,....) VALUES(데이터1, 데이터2, ....)
--INSERT INTO 테이블명 VALUES(데이터1, 데이터2, ....)
INSERT INTO PERSON(PNAME, AGE) VALUES('홍길동', 20);
INSERT INTO PERSON VALUES('김철수', 33);

--여러개 데이터 INSERT
INSERT ALL 
	INTO PERSON(PNAME, AGE) VALUES('김씨', 20)
	INTO PERSON VALUES('이씨', 30)
SELECT * FROM DUAL;

--학생 테이블 데이터 3건 등록하는 INSERT문 작성


