--그룹함수 테스트용 테이블
CREATE TABLE GROUP_TEST(
	CODE VARCHAR2(1),
	VAL NUMBER(3)
);

INSERT INTO GROUP_TEST VALUES('A',10);
INSERT INTO GROUP_TEST VALUES('B',20);
INSERT INTO GROUP_TEST VALUES('C',NULL);
INSERT INTO GROUP_TEST VALUES('D',30);
INSERT INTO GROUP_TEST VALUES('F',40);
--그룹함수는 NULL 값을 제외하고 계산함
SELECT SUM(VAL), AVG(VAL), AVG(NVL(VAL,0)),COUNT(*),COUNT(VAL)
FROM GROUP_TEST;
-------------------------------------------------------------------

